version: '3.6'

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: ./config/Dockerfile
      target: server
    restart: always
    volumes:
      - data:/var/www/html:ro
    healthcheck:
      test:  wget -q -t 1 --spider http://localhost || exit 1
      interval: 5m
      timeout: 3s
    environment:
      - VIRTUAL_HOST=ebelleon.de,www.ebelleon.de
      - LETSENCRYPT_HOST=ebelleon.de,www.ebelleon.de
      - LETSENCRYPT_EMAIL=ebel.leon@hotmail.com
    networks:
      - default
      - nginx-proxy_default

volumes:
  data:

networks:
  nginx-proxy_default:
    external: true
