version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    container_name: portfolio-web
    restart: always
    volumes:
      - data:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=ebelleon.de,www.ebelleon.de
      - LETSENCRYPT_HOST=ebelleon.de,www.ebelleon.de
      - LETSENCRYPT_EMAIL=ebel.leon@hotmail.com
    networks:
      - default
      - nginx-proxy_default

volumes:
  data:

networks:
  nginx-proxy_default:
    external: true
