version: '3'

services:
  portfolio:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: portfolio
    restart: always
    ports:
      - '8080:80'
    volumes:
      - files:/var/www/html:ro

volumes:
  files:
