# For full config options, check the docs:
#    docs.serverless.com

service: static-site-mailer

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  enviroment:
    NODE_ENV: dev
    EMAIL: "kontakt@ebelleon.de"
    DOMAIN: "https://ebelleon.de"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
    events:
      - http:
          method: post
          path: static-site-mailer
          cors: true

package:
  exclude:
    - ./**
  include:
    - ./handler.js

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**
